[mypy]
plugins = mypy_django_plugin.main
exclude = migrations|tests|build

[mypy.plugins.django-stubs]
django_settings_module = "aqua_setu.settings"

[mypy-phonenumber_field.*]
ignore_missing_imports = True

[mypy-import_export.*]
ignore_missing_imports = False

[mypy-filetype]
ignore_missing_imports = True

[mypy-drf_extra_fields.*]
ignore_missing_imports = True

[mypy-sequences.*]
ignore_missing_imports = True

[mypy-weasyprint.*]
ignore_missing_imports = True
